smartgateway:
        build: ./Smart_Gateway
        hostname: smartgateway
        expose:
                - 8181
                - 61616
                - 1883
        ports:
                - "8181:8181"
                - "61616:61616"
                - "1883:1883"
        environment:
                - LOCAL_BROKER_URL=tcp://localhost:61616
                - DATACENTER_BROKER_URL=tcp://localhost:61616
