- name: Configure a Pi to be a smart gateway for IoT
  hosts: gateways
  become: False
  tasks:
    - name: Build the Smart Gateway deployables
      local_action: command mvn install
      args:
        chdir: ./../Rules

    - name: Upload Rules deployable to Smart Gateway
      copy: src=./../Rules/target/rules-jar-with-dependencies.jar
            dest=/home/pi/IoT_Demo_Gateway/Rules/target/
